# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{constantrecord}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christoph Petschnig"]
  s.date = %q{2010-10-02}
  s.description = %q{A tiny ActiveRecord substitute for small, never changing database tables.}
  s.email = %q{info@purevirtual.de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "constantrecord.gemspec",
     "lib/constantrecord.rb",
     "samples/canadian_province.rb",
     "samples/german_province.rb",
     "samples/us_state.rb",
     "test/helper.rb",
     "test/test_constantrecord.rb"
  ]
  s.homepage = %q{http://github.com/cpetschnig/constantrecord}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A tiny ActiveRecord substitute for small, never changing database tables.}
  s.test_files = [
    "test/test_constantrecord.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

